[tool.poetry]
name = "poetry-venv"
version = "1"
description = "setup-codestyle practice"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyspark = "3.3.1"
pandas = "^2.2.3"
click = "8.0.1"
numpy = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
