version: '3'

services:
  pyspark:
    build: .
    container_name: pyspark_container
    environment:
      - PYARROW_IGNORE_TIMEZONE=1
    volumes:
      - .:/Pyspark

  linter:
    build: .  
    container_name: pylint_container
    environment:
      - PYLINTHOME=/tmp/.cache
    entrypoint: ["python", "-m", "pylint", "regular_patients/main.py", "regular_patients/regular_patients.py"]
    volumes:
      - .:/Pyspark

  tests:
    build: .  
    container_name: tests_container
    volumes:
      - ./tests:/Pyspark/tests  
    command: python -m pytest /Pyspark/tests/test_regular_patients.py