name: CI/CD for regular_patients_pyspark

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Start Containers
        working-directory: regular_patients_pyspark
        run: docker-compose up --build -d --force-recreate --remove-orphans

      - name: Run Pylint
        working-directory: regular_patients_pyspark
        run: docker-compose run --rm linter

      - name: Shut down containers
        working-directory: regular_patients_pyspark
        run: docker-compose down -v

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Start Containers
        working-directory: regular_patients_pyspark
        run: docker-compose up --build -d --force-recreate --remove-orphans

      - name: Run tests
        working-directory: regular_patients_pyspark
        run: docker-compose run --rm tests

      - name: Shut down containers
        working-directory: regular_patients_pyspark
        run: docker-compose down -v

  regular-patients:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Start Containers
        working-directory: regular_patients_pyspark
        run: docker-compose up --build -d --force-recreate --remove-orphans

      - name: Run regular-patients-main
        working-directory: regular_patients_pyspark
        run: docker-compose run --rm pyspark

      - name: Shut down containers
        working-directory: regular_patients_pyspark
        run: docker-compose down -v
